# Use the official Node.js 18 image.
FROM node:18-alpine

# Set the working directory in the container.
WORKDIR /app

# Copy package.json and package-lock.json to the working directory.
COPY package*.json ./

# Install project dependencies.
RUN npm install

# Copy the rest of the application code.
COPY . .

# Expose port 3000 to the outside world.
EXPOSE 3000

# Command to run the application in development mode.
CMD ["npm", "run", "dev"]
